version: '3'
services:
  gl-db:
    container_name: gl-mongo
    image: mongo:4.2
    networks:
      - app-network
    volumes:
      - ./src/dbdata:/app/src/data/db

  api:
    container_name: gl-api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - 3033:3033

networks:
  app-network:
