version: '3'
services:
  db:
    container_name: gl-mongo
    image: mongo:4.2
    networks:
      - app-network
    volumes:
      - ./src/dbdata:/app/src/data/db

  api:
    container_name: gl-api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - 3030:3030

networks:
  app-network:
